import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { BlankComponent } from './views/blank/blank.component';
import { LoginComponent } from './views/login/login.component';
import { PageLayoutComponent } from './views/page-layout/page-layout.component';
import { SimpleLayoutComponent } from './views/simple-layout/simple-layout.component';

const routes: Routes = [
  {
    path: "", pathMatch: "full", redirectTo: "/login"
  },
  // EAGER LOADING
  {
    path: "login",
    // nacitame prazdnou komponentu
    component: BlankComponent,
    // do ni nacitame login komponentu
    children: [
      {
        path: "",
        component: LoginComponent
      }
    ]
  },

  // S LAZY LOADINGEM
  {
    path: "todos",
    // nacitame komponentu, ktera ma v sobe layout
    component: PageLayoutComponent,
    // nacitame todos modul, ktery ma v sobe komponentu todos
    loadChildren: () => import('./views/todos/todos.module').then(module => module.TodosModule)
  },
  {
    path: "users",
    component: PageLayoutComponent,
    loadChildren: () => import('./views/users/users.module').then(module => module.UsersModule)
  },
  {
    path: "films",
    // nacitame komponentu, ktera ma v sobe layout
    component: SimpleLayoutComponent,
    // nacitame todos modul, ktery ma v sobe komponentu todos
    loadChildren: () => import('./views/films/films.module')
    .then(module => module.FilmsModule)
  },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
